# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - run: sudo apt-get install clang zlib1g-dev
    - name: Publish
      run: dotnet publish -r linux-x64 -c Release
    - name: Upload ConsoleApp
      uses: actions/upload-artifact@v4
      with:
        path: ConsoleApp/bin/Release/net9.0/linux-x64/publish/*
    - name: Upload DesktopApp
      uses: actions/upload-artifact@v4
      with:
        path: DesktopApp/bin/Release/net9.0/linux-x64/publish/*
